server/Detector/urls.py
from django.urls import path
from . import views
from.views import uploadXray, homepage, singleView, viewAllXrays, deleteXray

urlpatterns = [
    path('uploadXray/',uploadXray,name = 'uploadXray'),
    path('', homepage, name = 'homepage'),
    path('singleViewXray/<int:xray_id>/',singleView, name='singleView'),
    path('viewAllXrays/',viewAllXrays, name='viewAllXrays'),
    path('deleteXray/<int:xray_id>/',deleteXray, name= 'deleteXray')
]

server/authentication/urls.py
from django.urls import path
from .views import login_view, signup_view
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', signup_view, name="register"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Detector.urls')),
    path('', include('authentication.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

server/Detector/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Xrays(models.Model):
    patientName = models.CharField(max_length=30)
    uploadedBy = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    uploadedOn = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to = 'uploadedXrays/')
    confidence = models.FloatField(default=1)
    result = models.CharField(max_length=30)

server/authentication/models.py
from django.db import models

# Create your models here.

server/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

server/Detector/views.py
from django.shortcuts import render,redirect
# Create your views here.
from .models import Xrays
import json

## For Prediction
import torch
import torchvision
import torchvision.transforms as transforms
from PIL import Image

model = torchvision.models.resnet152(pretrained=False)
model.fc = torch.nn.Linear(2048,4)
model.load_state_dict(torch.load('../server/xyz_epoch_1.pt',map_location ='cpu'))
model.eval()


def homepage(request):
    if request.user.is_authenticated:
        return render(request, 'pages/homepage.html')
    else:
        return redirect('login')


def uploadXray(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            return render(request, 'pages/uploadPrescription.html')
        elif request.method == 'POST':
            image = request.FILES['xray_image']
            # print(request.POST['toSave'])
            try : 
                toSave = request.POST['toSave']
            except:
                toSave = False
            
            print(toSave)
            obj = Xrays(uploadedBy = request.user, image = image)
            obj.result = predictXray(obj)
            if toSave : 
                obj.save()
            return redirect('singleView', xray_id=obj.id)
    else:
        return redirect('login')

def singleView(request,xray_id):
    if request.user.is_authenticated:
        context = {
            'xray': Xrays.objects.get(id=xray_id) 
        }

        return render(request, 'pages/singleView.html', context=context)
    else:
        return redirect('login')


def viewAllXrays(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            obj = Xrays.objects.all()
            context = {
                'Xrays' : obj
            }
            
            return render(request, 'pages/viewPrescription.html', context=context)
    else:
        return redirect('login')


def deleteXray(request, xray_id):
    if request.user.is_authenticated:
        xray = Xrays.objects.get(id=xray_id)
        if request.user == xray.uploadedBy:
            xray.delete()
        return redirect( "homepage")
    else:
        return redirect('login')

classes = ['COVID', 'Lung_Opacity', 'Normal', 'Viral Pneumonia']
def predictXray(xray):
    img = Image.open(xray.image).convert('RGB')
    trans = transforms.Compose([transforms.ToTensor()])
    transimg = trans(img)
    with torch.no_grad():
        output = model(transimg.unsqueeze(0))
    return classes[torch.argmax(output).item()]

server/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm, SignUpForm

# Create your views here.
def login_view(request):
    form = LoginForm(request.POST or None)
    msg = None

    if request.user.is_authenticated:
        return redirect('/')

    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                msg = "Invalid Credentials"
        else:
            msg = "Error Validating Form Data"
        
    context = {
        "form": form,
        "msg": msg
    }
        
    return render(request, "pages/login_page.html", context=context)

def signup_view(request):
    if request.user.is_authenticated:
        return redirect('/login')
    msg = None
    success = None
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            msg = 'User created - please <a href="/login/">login</a>.'
            success = True
            # return redirect("/login/")
        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()
    
    context = {
        'form': form,
        'msg' : msg
    }
    return render(request, 'pages/signup_page.html', context=context)

server/templates/configuration-plugin.html
        <div class="custom-template">
			<div class="title">Settings</div>
			<div class="custom-content">
				<div class="switcher">
					<!-- <div class="switch-block">
						<h4>Logo Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
							<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
						</div>
					</div> -->
					<div class="switch-block">
						<h4>Navbar Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeTopBarColor" data-color="dark"></button>
							<button type="button" class="changeTopBarColor" data-color="blue"></button>
							<button type="button" class="changeTopBarColor" data-color="purple"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
							<button type="button" class="changeTopBarColor" data-color="green"></button>
							<button type="button" class="changeTopBarColor" data-color="orange"></button>
							<button type="button" class="changeTopBarColor" data-color="red"></button>
							<button type="button" class="changeTopBarColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeTopBarColor" data-color="dark2"></button>
							<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="purple2"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="green2"></button>
							<button type="button" class="changeTopBarColor" data-color="orange2"></button>
							<button type="button" class="changeTopBarColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Sidebar</h4>
						<div class="btnSwitch">
							<button type="button" class="selected changeSideBarColor" data-color="white"></button>
							<button type="button" class="changeSideBarColor" data-color="dark"></button>
							<button type="button" class="changeSideBarColor" data-color="dark2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Background</h4>
						<div class="btnSwitch">
							<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
							<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
							<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
							<button type="button" class="changeBackgroundColor" data-color="dark"></button>
						</div>
					</div>
				</div>
			</div>
			<div class="custom-toggle">
				<i class="flaticon-settings"></i>
			</div>
		</div>

        

server/templates/footer.html
<footer class="footer">
	<div class="container-fluid">
		<nav class="pull-left">
			<ul class="nav">
				<li class="nav-item">
					<a class="nav-link" 
						target="_blank" 
						href="https://github.com/adityarajsahu/Medecoder">
						Medecoder
					</a>
				</li>
			</ul>
		</nav>
		<div class="copyright ml-auto">
			&copy; <a target="_blank" href="https://github.com/adityarajsahu/Medecoder">Project</a> 
			- coded by <a target="_blank" href="https://github.com/adityarajsahu/Medecoder">REGEX</a>
		</div>				
	</div>
	
</footer>

<style>
	.footer {
	  position: fixed;
	  left: 0;
	  bottom: 0;
	  width: 100%;
	  text-align: center;
	}
	</style>

server/templates/layouts/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />

	<title>
        {% block title %}{% endblock %}
    </title>

	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="icon" href="/static/assets/img/icon.ico" type="image/x-icon"/>

	<!-- Fonts and icons -->
	<script src="/static/assets/js/plugin/webfont/webfont.min.js"></script>
	<script>
		WebFont.load({
			google: {"families":["Lato:300,400,700,900"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], 
			urls: ['/static/assets/css/fonts.min.css']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="/static/assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/assets/css/atlantis.css">
	<link rel="stylesheet" href="/static/assets/css/demo.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">


    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>
<body>
	<div class="wrapper">

        {% include 'navigation.html' %}

        {% include 'sidebar.html' %}

		<div class="main-panel">
			
			{% block content %}{% endblock content %}

			{% include 'footer.html' %}

		</div>

        {% if request.user.is_authenticated %}


		{% endif %}		

	</div>

	{% include 'scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>

server/templates/navigation.html
		<div class="main-header">

			<!-- Logo Header -->
			<div class="logo-header ">
				
				<a href="/" class="logo">
					<h1 class="brand-logo">MedeCoder</h1>
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
				</div>
			</div>
			<!-- End Logo Header -->

			<!-- Navbar Header -->
			<nav class="navbar navbar-header navbar-expand-lg navbarBG">
				<div class="container-fluid">
					{% if request.user.is_authenticated %}
					<div class="collapse" id="search-nav">
						<form class="navbar-left navbar-form nav-search mr-md-3" action="/viewPrescription/" method="post"	>
							<div class="input-group">
								<div class="input-group-prepend">
									<button type="submit" class="btn btn-search pr-1">
										<i class="fa fa-search search-icon"></i>
									</button>
								</div>
								{% csrf_token %}
								<input type="text" name="search" placeholder="Search ..." class="form-control" value="{{searched}}">
							</div>
						</form>
					</div>
					
					<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">			
						<li class="nav-item dropdown hidden-caret">
							<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
								<div class="avatar-sm">
									<img src="/static/assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
								</div>
							</a>
							<ul class="dropdown-menu dropdown-user animated fadeIn">
								<div class="dropdown-user-scroll scrollbar-outer">
									<li>
										<div class="user-box">
											<div class="avatar-lg"><img src="/static/assets/img/profile.jpg" alt="image profile" class="avatar-img rounded"></div>
											<div class="u-text">
												<h4>
													{{ request.user.username }}
												</h4>
												<p class="text-muted">
													{{ request.user.email }}
												</p>
											</div>
										</div>
									</li>
									<li>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="/logout/">Logout</a>
									</li>
								</div>
							</ul>
						</li>
						<li class="nav-item">
							<!-- <i class="fa fa-github"></i> -->
							<a class="profile-pic">
							</a>
						</li>
					</ul>
				</div>
				{% endif %}
			</nav>
			<!-- End Navbar -->
        </div>
        

server/templates/pages/homepage.html
{% extends "layouts/base1.html" %}

{% block title %} Homepage {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style>
    img {
        border-radius: 7px;
    }

    .zoom {
    transition: transform 0.2s;
  }
  .zoom:hover {
    transform: scale(1.1); 
    }
</style>

{% endblock stylesheets %}

{% block content %}

    <div class="page-inner">
        <div class="container-fluid mt-5">
            <div class="card">
                <div class="card-body">
                    <h1 class="page-title">Welcome {{request.user.username}}</h1>
                    
                </div>
                <div class="row">
                    <h3 >Your Uploaded Prescriptions</h3>
                    {% if request.user.xrays_set %}
                    
                    {% for xray in request.user.xrays_set.all %}
                    <div class="col-md-4">
                        <div class="card text-center m-3 p-3 zoom" style="border-radius: 1em;">
                            <div class="card-img">
                                <img src="{{xray.image.url}}" width="100%">
                            </div>
                            <div class="card-text">
                                <a href="/singleViewXray/{{xray.id}}/"><button class="btn btn-primary m-3">View</button></a>
                                <span>
                                    <a href="/deleteXray/{{xray.id}}/">
                                      <button class="btn btn-danger">Delete</button>
                                    </a>
                                  </span>
                            </div>
                            
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                        <!-- <h3>You have not uploaded prescriptions</h3> -->
                        <p>Start uploading your prescriptions <a href="/uploadXray/">here</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

server/templates/pages/login_page.html
{% extends "layouts/base1.html" %}

{% block title %} Login {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Login</h4>
            <ul class="breadcrumbs">
                <li class="nav-home">
                    <a href="#">
                        <i class="flaticon-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Authentication</a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Login</a>
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">

                            {% if msg %}
                                <span class="text-danger">{{ msg | safe }}</span>
                            {% else %}
                            <span>
                                Add your credentials
                            </span>
                            {% endif %}

                        </div>
                    </div>

                    <form method="post" action="">

                        {% csrf_token %}

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 col-lg-4">

                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="icon-user"></i>
                                                </span>
                                            </div>
                                            {{ form.username }}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="icon-lock"></i>
                                                </span>
                                            </div>
                                            {{ form.password }}
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="card-action">
                            <button type="submit" class="btn btn-success">Submit</button>
                            &nbsp; &nbsp;
                            <span>Not a member?</span> Please <a href="/register/" >Register</a>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

server/templates/pages/medication.html
<!-- Specific JS goes HERE -->
{% extends "layouts/base1.html" %}

{% block title %} View Medication {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="content">
    <div class="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-title">Predict Prescriptions</h4>
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Medications</div>
                    </div>
                    <div class="card-body">
                        <table class="table table-head-bg-success">
                            <thead>
                                <tr>
                                    
                                    <th scope="col">Medicine</th>
                                    <th scope="col">Dosage</th>
                                    <th scope="col">Frequency</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for m in med %}
                                <tr>
                                    {% for d in m %}
                                        <td>{{d}}</td>
                                    {% endfor %}
                                    
                                </tr> 
                                {% endfor %}
                
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Protected Health Information</div>
                    </div>
                    <div class="card-body">
                        <table class="table table-head-bg-success">
                            <thead>
                                <tr>
                                    
                                    <th scope="col">Name</th>
                                    <th scope="col">Type</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for m in protected_health_info %}
                                <tr>
                                    {% for d in m %}
                                        <td>{{d}}</td>
                                    {% endfor %}

                                </tr>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Treatment Procedures</div>
                    </div>
                    <div class="card-body">
                        <table class="table table-head-bg-success">
                            <thead>
                                <tr>
                                    
                                    <th scope="col">Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for m in test_treatment %}
                                <tr>
                                    <td>{{m}}</td>
                                </tr>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Medical Condition</div>
                    </div>
                    <div class="card-body">
                        <table class="table table-head-bg-success">
                            <thead>
                                <tr>
                                    
                                    <th scope="col">Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for m in medicalCondition %}
                                <tr>
                                    <td>{{m}}</td>
                                </tr>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Anatomy</div>
                    </div>
                    <div class="card-body">
                        <table class="table table-head-bg-success">
                            <thead>
                                <tr>
                                    
                                    <th scope="col">Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for m in Anatomy %}
                                <tr>
                                    <td>{{m}}</td>
                                </tr>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

	
{% endblock javascripts %}

server/templates/pages/singleView.html
{% extends "layouts/base1.html" %}

{% block title %} Single Prescription View {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style>
    .loader {
        border: 3px solid #f3f3f3; /* Light grey */
        border-top: 3px solid #3498db; /* Blue */
        border-radius: 50%;
        width: 21px;
        height: 21px;
        animation: spin 2s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>
{% endblock stylesheets %}

{% block content %}

<div class="content">
    <div class="page-inner">
        <!-- Card -->
        <!-- <h4 class="page-title">
            Uploaded By: {{prescription.uploaded_by.username}}<br>
            Uploaded On: {{prescription.uploaded_on}}
            
        </h4> -->
        <div class="row mt-5 pt-5 ml-3">
            <div class="col-md-6">
                <div class="card w-75 shadow-lg">
                    <div class="card-img">
                        <img width="100%" src="{{xray.image.url}}">
                        <h3 class="page-title ml-3 mt-2">
                        Uploaded by : {{xray.uploadedBy.username}}<br>
                        Uploaded on : {{xray.uploadedOn}}
                        </h3>
                    </div>
                </div>
            </div>
            <div class="col-md-6"  >
               <h2> Diesease Predicted : {{xray.result}}</h2>
                
            </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script type="text/javascript">  
    $(document).ready(function(){ 
        $("#alpanaRaButton").click(function(){
            var btn = document.getElementById('alpanaRaButton')
            btn.innerHTML = " <div class = 'd-flex'><div>Training &nbsp</div><span class='loader'></span></div>"
            btn.disabled = true
            setTimeout(()=>{
                var btn = document.getElementById('alpanaRaButton')
                btn.innerHTML = "Retrain"
                btn.disabled = false
            }, 10000)       
        });
    });   
</script> 
{% endblock javascripts %}